# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bojan.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 858)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bojan_kral.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background:#aaa;")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 495, 391))
        self.frame.setStyleSheet("background-color:#5CA2F1;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 441, 362))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stop_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.stop_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.stop_btn.setMaximumSize(QtCore.QSize(90, 16777215))
        self.stop_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("background-color: white;\n"
"color: rgb(69, 124, 182);\n"
"color: black;\n"
"border: 2px solid #457cb6;\n"
"border-radius:7%;")
        self.stop_btn.setObjectName("stop_btn")
        self.gridLayout_3.addWidget(self.stop_btn, 2, 3, 1, 1)
        self.vodenje = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.vodenje.setMinimumSize(QtCore.QSize(0, 30))
        self.vodenje.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.vodenje.setFont(font)
        self.vodenje.setStyleSheet("background-color: white;\n"
"color: rgb(69, 124, 182);\n"
"color: black;\n"
"border: 2px solid #457cb6;\n"
"border-radius:7%;")
        self.vodenje.setObjectName("vodenje")
        self.gridLayout_3.addWidget(self.vodenje, 4, 3, 1, 1)
        self.pause_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pause_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.pause_btn.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pause_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.pause_btn.setFont(font)
        self.pause_btn.setStyleSheet("background-color: white;\n"
"color: rgb(69, 124, 182);\n"
"color: black;\n"
"border: 2px solid #457cb6;\n"
"border-radius:7%;")
        self.pause_btn.setObjectName("pause_btn")
        self.gridLayout_3.addWidget(self.pause_btn, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 4, 1, 1, 1)
        self.y_inc = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.y_inc.setMinimumSize(QtCore.QSize(50, 50))
        self.y_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.y_inc.setFont(font)
        self.y_inc.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.y_inc.setStyleSheet("image: url(C:/Users/jakak/Desktop/Jaka/Šola/4.letnik/NEMI/bojan_interface/ui/img/puscica_gor.png);\n"
"background-color:white;\n"
"border-radius:25px;\n"
"")
        self.y_inc.setText("")
        self.y_inc.setObjectName("y_inc")
        self.gridLayout_3.addWidget(self.y_inc, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.calibrate_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.calibrate_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.calibrate_btn.setMaximumSize(QtCore.QSize(90, 16777215))
        self.calibrate_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.calibrate_btn.setFont(font)
        self.calibrate_btn.setStyleSheet("background-color: white;\n"
"color: rgb(69, 124, 182);\n"
"color: black;\n"
"border: 2px solid #457cb6;\n"
"border-radius:7%;")
        self.calibrate_btn.setObjectName("calibrate_btn")
        self.gridLayout_3.addWidget(self.calibrate_btn, 5, 3, 1, 1)
        self.x_inc = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.x_inc.setMinimumSize(QtCore.QSize(50, 50))
        self.x_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.x_inc.setFont(font)
        self.x_inc.setStyleSheet("image: url(C:/Users/jakak/Desktop/Jaka/Šola/4.letnik/NEMI/bojan_interface/ui/img/puscica_desno.png);\n"
"background-color:white;\n"
"border-radius:25px;")
        self.x_inc.setText("")
        self.x_inc.setObjectName("x_inc")
        self.gridLayout_3.addWidget(self.x_inc, 3, 2, 1, 1)
        self.y_decr = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.y_decr.setMinimumSize(QtCore.QSize(50, 50))
        self.y_decr.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.y_decr.setFont(font)
        self.y_decr.setStyleSheet("image: url(C:/Users/jakak/Desktop/Jaka/Šola/4.letnik/NEMI/bojan_interface/ui/img/puscica_dol.png);\n"
"background-color:white;\n"
"border-radius:25px;")
        self.y_decr.setText("")
        self.y_decr.setObjectName("y_decr")
        self.gridLayout_3.addWidget(self.y_decr, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 6, 1, 1, 1)
        self.play_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.play_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.play_btn.setMaximumSize(QtCore.QSize(90, 16777215))
        self.play_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.play_btn.setFont(font)
        self.play_btn.setStyleSheet("background-color: white;\n"
"color: rgb(69, 124, 182);\n"
"color: black;\n"
"border: 2px solid #457cb6;\n"
"border-radius:7%;")
        self.play_btn.setObjectName("play_btn")
        self.gridLayout_3.addWidget(self.play_btn, 1, 3, 1, 1)
        self.x_decr = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.x_decr.setMinimumSize(QtCore.QSize(50, 50))
        self.x_decr.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.x_decr.setFont(font)
        self.x_decr.setStyleSheet("image: url(C:/Users/jakak/Desktop/Jaka/Šola/4.letnik/NEMI/bojan_interface/ui/img/puscica_levo.png);\n"
"background-color:white;\n"
"border-radius:25px;")
        self.x_decr.setText("")
        self.x_decr.setObjectName("x_decr")
        self.gridLayout_3.addWidget(self.x_decr, 3, 0, 1, 1)
        self.velocitySlider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.velocitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.velocitySlider.setObjectName("velocitySlider")
        self.gridLayout_3.addWidget(self.velocitySlider, 6, 2, 1, 3)
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(510, 0, 495, 391))
        self.frame_3.setStyleSheet("background-color:#5CA2F1;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 131, 121))
        self.label_2.setStyleSheet("border:2px solid #457cb6;\n"
"border-image: url(C:/Users/jakak/Desktop/Jaka/Šola/4.letnik/NEMI/bojan_interface/ui/img/bojan_kral.jpg);\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 140, 461, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.x_poz = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.x_poz.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.x_poz.setFont(font)
        self.x_poz.setStyleSheet("background-color:white;\n"
"border:2px solid #457cb6;\n"
"color: black;\n"
"font: 8pt \"Luckiest Guy\";")
        self.x_poz.setFrameShape(QtWidgets.QFrame.Box)
        self.x_poz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.x_poz.setLineWidth(1)
        self.x_poz.setMidLineWidth(1)
        self.x_poz.setText("")
        self.x_poz.setObjectName("x_poz")
        self.gridLayout_4.addWidget(self.x_poz, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.z_poz = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.z_poz.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.z_poz.setFont(font)
        self.z_poz.setStyleSheet("background-color:white;\n"
"border:2px solid #457cb6;\n"
"color: black;\n"
"font: 8pt \"Luckiest Guy\";")
        self.z_poz.setFrameShape(QtWidgets.QFrame.Box)
        self.z_poz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.z_poz.setLineWidth(1)
        self.z_poz.setMidLineWidth(1)
        self.z_poz.setText("")
        self.z_poz.setObjectName("z_poz")
        self.gridLayout_4.addWidget(self.z_poz, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.y_poz = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.y_poz.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.y_poz.setFont(font)
        self.y_poz.setStyleSheet("background-color:white;\n"
"border:2px solid #457cb6;\n"
"color: black;\n"
"font: 8pt \"Luckiest Guy\";")
        self.y_poz.setFrameShape(QtWidgets.QFrame.Box)
        self.y_poz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.y_poz.setLineWidth(1)
        self.y_poz.setMidLineWidth(1)
        self.y_poz.setText("")
        self.y_poz.setObjectName("y_poz")
        self.gridLayout_4.addWidget(self.y_poz, 3, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 9, 321, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_img_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.load_img_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        self.load_img_btn.setFont(font)
        self.load_img_btn.setStyleSheet("background-color: white;\n"
"color: rgb(69, 124, 182);\n"
"color: black;\n"
"border: 2px solid #457cb6;\n"
"border-radius:7%;")
        self.load_img_btn.setObjectName("load_img_btn")
        self.verticalLayout.addWidget(self.load_img_btn)
        self.x_poz_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.x_poz_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.x_poz_2.setFont(font)
        self.x_poz_2.setStyleSheet("background-color:white;\n"
"border:2px solid #457cb6;\n"
"color: black;\n"
"font: 8pt \"Luckiest Guy\";")
        self.x_poz_2.setFrameShape(QtWidgets.QFrame.Box)
        self.x_poz_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.x_poz_2.setLineWidth(1)
        self.x_poz_2.setMidLineWidth(1)
        self.x_poz_2.setObjectName("x_poz_2")
        self.verticalLayout.addWidget(self.x_poz_2)
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setGeometry(QtCore.QRect(0, 410, 495, 401))
        self.frame_4.setStyleSheet("background-color:#5CA2F1;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 440, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(510, 410, 495, 401))
        self.frame_2.setStyleSheet("background-color:#5CA2F1;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.predogled = QtWidgets.QGraphicsView(self.frame_2)
        self.predogled.setGeometry(QtCore.QRect(20, 30, 461, 351))
        self.predogled.setStyleSheet("background-color:#ffffff;")
        self.predogled.setObjectName("predogled")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 440, 26))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setStyleSheet("background-color:#5CA2F1;")
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setStyleSheet("background-color:white;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5.addWidget(self.frame_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bojan"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.vodenje.setText(_translate("MainWindow", "vodenje"))
        self.pause_btn.setText(_translate("MainWindow", "Pavza"))
        self.label.setText(_translate("MainWindow", "JOG"))
        self.calibrate_btn.setText(_translate("MainWindow", "Kalibriraj"))
        self.play_btn.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "TRENUTNA POZICIJA Z"))
        self.label_3.setText(_translate("MainWindow", "TRENUTNA POZICIJA X"))
        self.label_5.setText(_translate("MainWindow", "TRENUTNA POZICIJA Y"))
        self.load_img_btn.setText(_translate("MainWindow", "Naloži sliko"))
        self.x_poz_2.setText(_translate("MainWindow", "Ime datoteke"))
        self.label_4.setText(_translate("MainWindow", "    Ukazi (GCODE)"))
        self.label_6.setText(_translate("MainWindow", "     Predogled"))
